name: test_self_runner
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, label-beauty-az-cli]

    steps:

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
