name: Create self-hosted runner
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create self-hosted runner vm
        run: |
          az group create \
            --name rg_runner \
            --location westeurope

          az vm create \
            --resource-group rg_runner \
            --name runner \
            --image Ubuntu2204 \
            --admin-username pierrc \
            --admin-password Password123$ \
            --custom-data ./az_cli/gh.sh \
            --size Standard_B1s \
            --public-ip-address-dns-name runner00


