name: test_self_runner_docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Installation Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash