name: test_self_runner_docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: login azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}