name: test_self_runner_docker
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Version Az CLI
        run: |
          az --version

      - name: Version Terraform
        run: |
          terraform version